name: ğŸš€ Verify Secrets

on:
  push:
    branches:
      - main

jobs:
  verify-secrets:
    name: ğŸ‰ Verify Secrets
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ•µï¸ Verify Secrets
        run: |
          echo "FTP Server: ${{ secrets.FTP_SERVER }}"
          echo "FTP Username: ${{ secrets.FTP_USERNAME }}"
          echo "Password is set"